language: generic
matrix:
    include:
        - os: linux
          env: CC=gcc-5
          addons:
              apt:
                  packages:
                      - gcc-5
                  sources:
                      - llvm-toolchain-precise-3.8
                      - ubuntu-toolchain-r-test
        - os: linux
          env: CC=clang-3.8
          addons:
              apt:
                  packages:
                      - clang-3.8
                  sources: *sources
script: cd test && make run-test
